Dropdown for Channel-Selection
Eco-DiscordLink/EcoDiscordPlugin pull request #87
Opened 2023-03-10 09:54 UTC by JulianMa

* Migrated Channel type to ulong
* Dropdown will show all to the bot visible channels

2023-03-10 13:27 UTC, JulianMa commented
Some Preview:
![image](https://user-images.githubusercontent.com/10810443/224327888-faad51b2-0e23-4700-9dc6-d6fc997c42c9.png)

2023-03-14 19:51 UTC, MonzUn requested changes

2023-03-14 19:51 UTC, MonzUn commented on DiscordLink/Source/Data/ChannelLink.cs
> +        private void migrateOldChannelName()
Function names use `CamelCase`

2023-03-14 19:51 UTC, MonzUn commented on DiscordLink/Source/Data/DiscordChannelNameTypeConverter.cs
> +        private string formatChannelString(DiscordChannel discordChannel)
Camel case

2023-03-14 20:45 UTC, MonzUn approved these changes

2023-03-14 20:45 UTC, merged