Add Basic WebAPI support
Eco-DiscordLink/EcoDiscordPlugin pull request #88
Opened 2023-05-06 06:33 UTC by bombitmanbomb

Adds basic functionality and documentation for DiscordLink to the AdminWebAPI. 
- Restarting the Plugin
- Config Validation
- View Plugin Status
- Posting Invites

All calls require the AdminAPIToken (Header `X-API-KEY`) else 401 response.

![image](https://user-images.githubusercontent.com/11261721/236603639-67cf7b77-e520-4f11-a06a-06a2fbc6690b.png)

2023-05-06 06:51 UTC, bombitmanbomb commented on DiscordLink/DiscordLink.csproj
> +	</Reference>
I cannot for the life of me seem to be able to fix the indenting. Tabs keep being inserted.

2023-07-29 22:33 UTC, MonzUn commented
Hey, sorry it took so long for me to get to this one. Been a lot going on to say the least ^^'
It looks good, but I don't see the code for the AdminAPIToken, is that handled via the webserver code?

2023-07-29 23:44 UTC, bombitmanbomb commented
Yes, the controller handles all auth. `[Authorize(Policy = PolicyNames.RequireAdmin)]`
Non admin requests give a 401.

2023-08-03 12:27 UTC, JulianMa commented
oh.. i also totally forgot about this one, i'm sorry. There is so much going in right now, i don't know if i have time to properly review this anytime soon

2023-11-30 07:59 UTC, JulianMa commented on DiscordLink/DiscordLink.csproj
> +	</Reference>
thats odd, what IDE are you using?

2023-11-30 07:59 UTC, JulianMa commented on DiscordLink/Source/WebApi/V1/DiscordLinkController.cs
> +    [Route("discordlink/api/v1")]
I feel like we should stay closer to the vanilla path conventions, what do you think about `/api/v1/plugins/discordlink/` or, to be more seperated from the vanilla stuff, `/api/v1/discordlink` as base path?

2023-11-30 08:01 UTC, JulianMa commented
@bombitmanbomb sorry for the long time no update, but we haven't really worked on DiscordLink. Right now, we're preparing for the upcoming release of eco 10.0. So we will release DiscordLink 3.4 at some point.

2023-11-30 08:07 UTC, JulianMa commented on DiscordLink/Source/WebApi/V1/DiscordLinkController.cs
> +        [HttpGet("status/config")]
We already have the vanilla `api/v1/plugins/config/DiscordLink` endpoint, so i feel like this duplicates some stuff.
This feels like it's just a status, not a config, so `[HttpGet("status")]` feels more consistent

2023-11-30 08:07 UTC, JulianMa commented on DiscordLink/Source/WebApi/V1/DiscordLinkController.cs
> +                BotToken = !string.IsNullOrWhiteSpace(config.BotToken),
already in vanilla config

2023-11-30 08:07 UTC, JulianMa commented on DiscordLink/Source/WebApi/V1/DiscordLinkController.cs
> +                ServerId = config.DiscordServerID != 0,
already in vanilla config

2023-11-30 08:07 UTC, JulianMa commented on DiscordLink/Source/Commands/SharedCommands.cs
> +            else if (source == CommandInterface.Discord)
is this check necessary?

2023-11-30 08:07 UTC, JulianMa commented on DiscordLink/Source/Commands/SharedCommands.cs
> +            else if (source == CommandInterface.Discord)
is this check necessary?

2023-11-30 08:09 UTC, JulianMa requested changes
Can you adjust the things i mentioned?

2024-07-23 09:59 UTC, closed without merging

2024-07-23 09:59 UTC, MonzUn commented
Closing due to lack of response from author.